services:
  jenkins:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jenkins
    restart: unless-stopped
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8080:8080
      - 50000:50000
    networks:
      - jenkins_net

  agent:
    build:
      context: .
      dockerfile: ./Dockerfile.agent
    container_name: agentX
    init: true
    environment:
      JENKINS_URL: http://jenkins:8080          
      JENKINS_SECRET: ${JENKINS_SECRET}
      JENKINS_AGENT_NAME: agentX
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent       
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    networks:
      - jenkins_net
    depends_on:
      - jenkins                            

networks:
  jenkins_net:

volumes:
  jenkins_home: